language: ruby
cache: bundler
install: rake install
before_script: rake prepare_build_destination
script: rake build
after_success: rake deploy
branches:
  only:
    - source
env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
